export const QUERY_KEYS = {
  ALL_DESIGN: "All Design",
  USER_DESIGN: "User Design",
  ADMIN_DATA: "Admin Data",
  PAYMENT_REPORT: "Payment Report",
  USER_DASHBOARD: "User Dashboard",
  APPLICATION_DURATION: "Application Duration",
  USER_LIST: "User List",
  COMMENT_LIST: "Comment List",
  PAYMENT_ANALYTICS: "Payment Analytics",
  SINGLE_DESIGN: "Single Design",
  RELATED_DESIGN: "Related Design",
  ALL_APPLICATION: "All Applications",
  PROFILE_DESIGN: "Profile Design",
};
